name: CI/CD Pipeline for CloudSim Simulation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-simulate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package

      - name: Create and configure output directory
        run: |
          mkdir -p $GITHUB_WORKSPACE/output
          chmod 777 $GITHUB_WORKSPACE/output

      - name: Run CloudSim Simulation
        run: |
          mvn exec:java -pl modules/cloudsim-examples/ -Dexec.mainClass=org.cloudbus.cloudsim.examples.CloudSimPlusExample

      - name: Display Simulation Results
        run: cat $GITHUB_WORKSPACE/output/simulation_results.txt

      - name: Upload Simulation Results
        uses: actions/upload-artifact@v4
        with:
          name: simulation-results
          path: $GITHUB_WORKSPACE/output/simulation_results.txt